[package]
name = "iso_8859_1"
version = "0.0.1"
authors = ["Phlopsi <nbphobos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "*"
serde = "*"
